config/routes.rb
InstasalesServer::Application.routes.draw do  

  match 'users/search/', :controller => 'users', :action => 'search', :via => 'get', defaults: {format: :json}
  match 'products/search/', :controller => 'products', :action => 'search', :via => 'get', defaults: {format: :json}
  match 'tags/search/', :controller => 'tags', :action => 'search', :via => 'get', defaults: {format: :json}

  match 'followers/', :controller => 'follows', :action => 'followers', :via => 'get', defaults: {format: :json}
  match 'following/', :controller => 'follows', :action => 'following', :via => 'get', defaults: {format: :json}
  match 'follow/', :controller => 'follows', :action => 'follow', :via => 'post', defaults: {format: :json}
  match 'unfollow/', :controller => 'follows', :action => 'unfollow', :via => 'delete', defaults: {format: :json}

  resources :activities, defaults: {format: :json}  

  devise_for :users, :controllers => { :sessions => "sessions" }
  
  devise_scope :user do    
    resources :sessions, :only => [:create, :destroy], defaults: {format: :json}         
  end
  
  resources :users, :only => [:create, :show, :update, :edit, :destroy], defaults: {format: :json}

  resources :products, :except => [:new, :edit, :update], defaults: {format: :json} do    
    resources :comments, :except => [:index, :show], defaults: {format: :json}
    resources :likes, :only => [:create, :destroy, :index], defaults: {format: :json}
  end     

  root :controller => "products", :action => "index", :defaults => {:format => :json}

  

end

app/models/like.rb
class Like < ActiveRecord::Base
	belongs_to :user
	belongs_to :product

	validates_uniqueness_of :user_id, :scope => :product_id
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_like, only: [:show, :edit, :update, :destroy]

  # GET /likes
  # GET /likes.json
  def index
    @likes = current_user.likes

    # pagination
    if params[:page].to_i <= Kaminari.paginate_array(@likes).page(1).per(10).num_pages
      @likes = Kaminari.paginate_array(@likes).page(params[:page]).per(10)
      return @likes
    end

    @likes = nil
    
  end

  # GET /likes/1
  # GET /likes/1.json
  def show
  end

  # GET /likes/new
  def new
    @like = Like.new
  end

  # GET /likes/1/edit
  def edit
  end

  # POST /likes
  # POST /likes.json
  def create
    @like = Like.new(like_params)
    @like.user_id = current_user.id

    respond_to do |format|
      if @like.save
        format.html { redirect_to @like, notice: 'Like was successfully created.' }
        format.json { render action: 'show', status: :created, location: @like }
      else
        format.html { render action: 'new' }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /likes/1
  # PATCH/PUT /likes/1.json
  def update
    respond_to do |format|
      if @like.update(like_params)
        format.html { redirect_to @like, notice: 'Like was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /likes/1
  # DELETE /likes/1.json
  def destroy
    @like.destroy
    respond_to do |format|
      format.html { redirect_to likes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_like
      @like = Like.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def like_params
      params.require(:like).permit(:user_id, :product_id)
    end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_form.html.erb
<%= form_for(@like) do |f| %>
  <% if @like.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@like.errors.count, "error") %> prohibited this like from being saved:</h2>

      <ul>
      <% @like.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.number_field :product_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/likes/edit.html.erb
<h1>Editing like</h1>

<%= render 'form' %>

<%= link_to 'Show', @like %> |
<%= link_to 'Back', likes_path %>

app/views/likes/index.html.erb
<h1>Listing likes</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Product</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @likes.each do |like| %>
      <tr>
        <td><%= like.user_id %></td>
        <td><%= like.product_id %></td>
        <td><%= link_to 'Show', like %></td>
        <td><%= link_to 'Edit', edit_like_path(like) %></td>
        <td><%= link_to 'Destroy', like, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Like', new_like_path %>

app/views/likes/new.html.erb
<h1>New like</h1>

<%= render 'form' %>

<%= link_to 'Back', likes_path %>

app/views/likes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @like.user_id %>
</p>

<p>
  <strong>Product:</strong>
  <%= @like.product_id %>
</p>

<%= link_to 'Edit', edit_like_path(@like) %> |
<%= link_to 'Back', likes_path %>